### ISSUE TITLE
Uncaught TypeError: Cannot read property '0' of null

### ISSUE THREAD

**Issue by Jreyno40** [yasuyuky/autocomplete-clang#148]
[Steps to reproduce:]

1. Using goto declaration on a class

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.11.6
**Thrown From**: [autocomplete-clang](https://github.com/yasuyuky/autocomplete-clang) package 0.11.0

### Stack Trace

Uncaught TypeError: Cannot read property '0' of null

```
At /Users/jreyno40/.atom/packages/autocomplete-clang/lib/autocomplete-clang.coffee:133

TypeError: Cannot read property '0' of null
    at Object.parseAstDump (/packages/autocomplete-clang/lib/autocomplete-clang.coffee:133:10)
    at Object.handleGoDeclarationResult (/packages/autocomplete-clang/lib/autocomplete-clang.coffee:107:15)
    at /packages/autocomplete-clang/lib/autocomplete-clang.coffee:87:16
    at exit (/packages/autocomplete-clang/lib/clang-args-builder.coffee:23:25)
    at triggerExitCallback (/app.asar/src/buffered-process.js:322:11)
    at /app.asar/src/buffered-process.js:335:11
    at /app.asar/src/buffered-process.js:204:9)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12)
```

### Commands

```
     -2:49.2.0 autocomplete-clang:go-declaration (span.syntax--entity.syntax--name.syntax--function.syntax--c)
     -2:39.6.0 atom-ctags:go-to-declaration (span.syntax--entity.syntax--name.syntax--function.syntax--c)
     -2:29.3.0 atom-ctags:toggle-project-symbols (input.hidden-input)
     -2:21.5.0 atom-ctags:go-to-declaration (span.syntax--entity.syntax--name.syntax--function.syntax--c)
     -2:17.2.0 atom-ctags:rebuild (span.syntax--entity.syntax--name.syntax--function.syntax--c)
     -2:08.5.0 autocomplete-clang:go-declaration (span.syntax--entity.syntax--name.syntax--function.syntax--c)
     -1:50.8.0 atom-ctags:go-to-declaration (span.syntax--entity.syntax--name.syntax--function.syntax--c)
     -1:45.9.0 autocomplete-clang:go-declaration (span.syntax--entity.syntax--name.syntax--function.syntax--c)
     -0:21.2.0 atom-ctags:go-to-declaration (span.syntax--entity.syntax--name.syntax--function.syntax--c)
     -0:15.3.0 autocomplete-clang:go-declaration (span.syntax--entity.syntax--name.syntax--function.syntax--c)
```

### Non-Core Packages

```
an-old-hope-syntax 1.0.4 
atom-beautify 0.29.23 
atom-ctags 5.0.0 
atomify 0.3.0 
autocomplete-clang 0.11.0 
build-make 0.13.0 
busy-signal 1.3.0 
gpp-compiler 3.0.7 
intentions 1.1.2 
language-latex 1.0.0 
language-lua 0.9.11 
latex 0.43.0 
linter 2.1.4 
linter-clang 4.1.1 
linter-cppcheck 0.2.3 
linter-ui-default 1.2.3 
linter-write-good 0.9.0 
minimap 4.27.1 
minimap-linter 2.0.0 
platformio-ide-terminal 2.5.0 
symbol-gen 1.3.1 
tabs-to-spaces 1.0.3 
terminal-plus 0.14.5 
vim-mode 0.66.0 
```

**Comment by AStupidBear** [comment]
I have the same issue.

**Comment by rumata28** [comment]
+1

**Comment by alptiginsaki** [comment]
+1

**Comment by robchou** [comment]
+1

**Comment by chys87** [comment]
Same here

**Comment by wjm0621** [comment]
I Have Same issue

**Comment by ChristopherRabotin** [comment]
Same here, but it also happens on some functions in a `c` source file.

**Comment by Spongman** [comment]
the bug is because autocompelte-clang can't handle libraries whose paths contain spaces.

**Comment by Piot** [comment]
same here

**Comment by yasuyuky** [comment]
Now this problem seems to be fixed.
If not, feel free to reopen. 
Thanks for your feedbacks.

**Comment by Spongman** [comment]
Which commit fixed this?

**Comment by yasuyuky** [comment]
I expect this commit fixed

https://github.com/yasuyuky/autocomplete-clang/commit/7ce599b44357c5b66c61341cb396ef4a2204f3e8
