### ISSUE TITLE
Uncaught SyntaxError: Invalid regular expression: /^Dumping/s(?:[A-Za-z_]*::)*?*):/: Nothing to r...

### ISSUE THREAD

**Issue by futuriste** [yasuyuky/autocomplete-clang#182]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.37.0 x64
**Electron**: 2.0.18
**OS**: Unknown Windows version
**Thrown From**: [autocomplete-clang](https://github.com/yasuyuky/autocomplete-clang) package 0.11.5

### Stack Trace

Uncaught SyntaxError: Invalid regular expression: /^Dumping\s(?:[A-Za-z_]*::)*?*):/: Nothing to repeat

```
At C:\Users\kouam\.atom\packages\autocomplete-clang\lib\autocomplete-clang.coffee:126

SyntaxError: Invalid regular expression: /^Dumping\s(?:[A-Za-z_]*::)*?*):/: Nothing to repeat
    at RegExp (<anonymous>)
    at Object.parseAstDump (/packages/autocomplete-clang/lib/autocomplete-clang.coffee:126:31)
    at Object.handleGoDeclarationResult (/packages/autocomplete-clang/lib/autocomplete-clang.coffee:107:15)
    at /packages/autocomplete-clang/lib/autocomplete-clang.coffee:87:16
    at exit (/packages/autocomplete-clang/lib/clang-args-builder.coffee:23:25)
    at n (~/AppData/Local/atom/app-1.37.0/resources/app/static/<embedded>:14:1043822)
    at ChildProcess.o.process.on.e (~/AppData/Local/atom/app-1.37.0/resources/app/static/<embedded>:14:1044028)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
```

### Commands

```
     -9:56.7.0 editor:newline (input.hidden-input)
     -9:55.9.0 intentions:highlight (input.hidden-input)
     -9:55.8.0 core:paste (input.hidden-input)
     -9:49.5.0 core:copy (span.syntax--string.syntax--quoted.syntax--other)
     -9:46.1.0 platformio-ide:target:build (input.hidden-input)
     -9:46.1.0 platformio-ide:target:build-C:\Users\kouam\Documents\GitHub\nfc_reader_with_esp8266 (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
  2x -0:42.8.0 editor:newline (input.hidden-input)
     -0:25.9.0 autocomplete-plus:confirm (input.hidden-input)
     -0:17 autocomplete-clang:go-declaration (span.syntax--entity.syntax--name.syntax--function)
```

### Non-Core Packages

```
autocomplete-clang 0.11.5 
build 0.70.0 
busy-signal 2.0.1 
file-icons 2.1.32 
french-menu 0.2.2 
goto-definition 1.3.4 
intentions 1.1.5 
language-ini 1.20.0 
linter 2.3.0 
linter-gcc 0.7.1 
linter-ui-default 1.7.1 
platformio-aia 0.0.5 
platformio-ide 2.3.1 
platformio-ide-debugger 1.2.6 
platformio-ide-terminal 2.9.1 
tool-bar 1.1.11 
```

**Comment by yasuyuky** [comment]
Maybe this is a dup of #141
