### ISSUE TITLE
Uncaught TypeError: element.innerHTML is not a function

### ISSUE THREAD

**Issue by Adri1G** [yasuyuky/autocomplete-clang#183]
1. right click on called function
2. select go to declaration

**Atom**: 1.38.2 x64
**Electron**: 2.0.18
**OS**: Windows 7
**Thrown From**: [autocomplete-clang](https://github.com/yasuyuky/autocomplete-clang) package 0.12.0

### Stack Trace

Uncaught TypeError: element.innerHTML is not a function

```
At C:\Users\a.gauche\.atom\packages\autocomplete-clang\lib\jumper.coffee:44

TypeError: element.innerHTML is not a function
    at Object.elementForItem (/packages/autocomplete-clang/lib/jumper.coffee:44:19)
    at listItems.items.map (/packages/autocomplete-clang/node_modules/atom-select-list/src/select-list-view.js:219:31)
    at Array.map (<anonymous>)
    at SelectListView.renderItems (/packages/autocomplete-clang/node_modules/atom-select-list/src/select-list-view.js:215:35)
    at SelectListView.render (/packages/autocomplete-clang/node_modules/atom-select-list/src/select-list-view.js:199:12)
    at Object.initialize (/packages/teletype/node_modules/etch/lib/component-helpers.js:32:31)
    at /packages/autocomplete-clang/node_modules/atom-select-list/src/select-list-view.js:25:10)
    at Object.createDeclList (/packages/autocomplete-clang/lib/jumper.coffee:36:5)
    at Object.handleAstDumpResult (/packages/autocomplete-clang/lib/jumper.coffee:30:19)
    at /packages/autocomplete-clang/lib/jumper.coffee:21:16
    at exit (/packages/autocomplete-clang/lib/clang-args-builder.coffee:24:25)
    at n (~/AppData/Local/atom/app-1.38.2/resources/app/static/<embedded>:14:1119384)
    at ChildProcess.o.process.on.e (~/AppData/Local/atom/app-1.38.2/resources/app/static/<embedded>:14:1119590)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
```

### Commands

```
     -7:11.8.0 autocomplete-clang:go-declaration (span.syntax--source.syntax--cpp)
     -7:04.6.0 autocomplete-clang:toggle (span.syntax--source.syntax--cpp)
     -6:49.6.0 platformio-ide-debugger:toggle-cli (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui.teletype-Authenticated)
     -6:45.1.0 platformio-ide-debugger:disconnect (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui.teletype-Authenticated)
  2x -6:35.8.0 autocomplete-clang:toggle (span.syntax--entity.syntax--name.syntax--function)
     -5:19.4.0 platformio-ide:settings:pkg-linter (div.tool-panel.tree-view)
     -3:25.4.0 platformio-ide:settings:pkg-minimap (button.btn.icon.enablement.icon-playback-pause)
     -2:58.2.0 platformio-ide:settings:pkg-tool-bar (button.btn.icon.enablement.icon-playback-pause)
     -2:40 platformio-ide:settings:pkg-build (div.package-detail)
     -1:12.2.0 tree-view:move (span.name.icon.arduino-icon)
  4x -1:10.2.0 core:backspace (input.hidden-input)
     -1:07.8.0 core:confirm (input.hidden-input)
     -0:43.7.0 autocomplete-clang:toggle (div.line.cursor-line)
  2x -0:40.8.0 minimap:toggle (div.line)
  2x -0:36.2.0 symbols-tree-view:toggle (div.line)
     -0:25.6.0 autocomplete-clang:go-declaration (span.syntax--entity.syntax--name.syntax--function)
```

### Non-Core Packages

```
atom-ctags 5.1.2 
atom-html-preview 0.2.6 
autocomplete-clang 0.12.0 
build 0.70.0 
busy-signal 2.0.1 
compare-files 0.8.1 
docblockr 0.13.7 
file-icons 2.1.33 
highlight-selected 0.16.0 
intentions 1.1.5 
language-ini 1.21.0 
linter 2.3.0 
linter-gcc 0.7.1 
linter-gcc2 0.8.7 
linter-ui-default 1.7.1 
minimap 4.29.9 
pigments 0.40.2 
platformio-ide 2.3.1 
platformio-ide-debugger 1.2.6 
platformio-ide-terminal 2.9.1 
split-diff 1.6.0 
symbols-tree-view 0.14.0 
teletype 0.13.4 
todo-show 2.3.2 
tool-bar 1.1.11 
```

**Comment by rejnok93** [comment]
[Enter steps to reproduce:]

1. right click on called function
2. select go to declaration

**Atom**: 1.48.0 x64
**Electron**: 5.0.13
**OS**: Mac OS X 10.11.6
**Thrown From**: [autocomplete-clang](https://github.com/yasuyuky/autocomplete-clang) package 0.13.1


### Stack Trace

Uncaught TypeError: element.innerHTML is not a function

```
At /Users/rejnok/.atom/packages/autocomplete-clang/lib/jumper.coffee:44

TypeError: element.innerHTML is not a function
    at Object.elementForItem (/packages/autocomplete-clang/lib/jumper.coffee:44:19)
    at /packages/autocomplete-clang/node_modules/atom-select-list/src/select-list-view.js:219:31
    at Array.map (<anonymous>)
    at SelectListView.renderItems (/packages/autocomplete-clang/node_modules/atom-select-list/src/select-list-view.js:215:35)
    at SelectListView.render (/packages/autocomplete-clang/node_modules/atom-select-list/src/select-list-view.js:199:12)
    at Object.initialize (/packages/autocomplete-clang/node_modules/etch/lib/component-helpers.js:32:31)
    at /packages/autocomplete-clang/node_modules/atom-select-list/src/select-list-view.js:25:10)
    at Object.createDeclList (/packages/autocomplete-clang/lib/jumper.coffee:36:5)
    at Object.handleAstDumpResult (/packages/autocomplete-clang/lib/jumper.coffee:30:19)
    at /packages/autocomplete-clang/lib/jumper.coffee:21:16
    at exit (/packages/autocomplete-clang/lib/clang-args-builder.coffee:24:25)
    at n (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1063432)
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1063520
    at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1062188)
    at Socket.emit (events.js:199:15)
    at Pipe.<anonymous> (net.js:593:12)
```

### Commands

```
     -3:07.1.0 find-and-replace:show (input.hidden-input)
     -3:04.2.0 core:backspace (input.hidden-input)
  2x -2:21 atom-over-and-back:navigate-backward (input.hidden-input)
     -1:12 intentions:highlight (input.hidden-input)
     -1:11.8.0 autocomplete-clang:go-declaration (input.hidden-input)
```

### Non-Core Packages

```
atom-over-and-back 0.4.0 
autocomplete-clang 0.13.1 
build 0.70.0 
busy-signal 2.0.1 
file-icons 2.1.41 
goto-definition 1.3.4 
hyperclick 0.1.5 
intentions 1.1.5 
language-ini 1.23.0 
linter 2.3.1 
linter-gcc2 0.8.8 
linter-ui-default 1.8.1 
platformio-ide 2.7.1 
platformio-ide-debugger 1.2.6 
platformio-ide-terminal 2.10.0 
tool-bar 1.3.0 
```
