### ISSUE TITLE
Uncaught TypeError: Cannot read property 'toString' of null

### ISSUE THREAD

**Issue by benogle** [yasuyuky/autocomplete-clang#20]
_From @matan129 on December 10, 2014 9:59_

Uncaught TypeError: Cannot read property 'toString' of null

**Atom Version**: 0.155.0
**System**: linux 3.13.0-40-generic
**Thrown From**: Atom Core
### Steps To Reproduce
1. Open a new file
2. Change its type to c++
3. Type "#" (without quotation marks)
### Stack Trace

```
At /usr/share/atom/resources/app/node_modules/text-buffer/lib/history.js:121

TypeError: Cannot read property 'toString' of null
  at AutocompleteClangView.module.exports.AutocompleteClangView.handleCompletionResult (/home/matan/.atom/packages/autocomplete-clang/lib/autocomplete-clang-view.coffee:142:32)
  at AutocompleteClangView.module.exports.AutocompleteClangView.codeCompletionAt (/home/matan/.atom/packages/autocomplete-clang/lib/autocomplete-clang-view.coffee:106:6)
  at AutocompleteClangView.module.exports.AutocompleteClangView.buildWordList (/home/matan/.atom/packages/autocomplete-clang/lib/autocomplete-clang-view.coffee:99:6)
  at AutocompleteClangView.module.exports.AutocompleteClangView.attach (/home/matan/.atom/packages/autocomplete-clang/lib/autocomplete-clang-view.coffee:87:14)
  at AutocompleteClangView.module.exports.AutocompleteClangView.toggle (/home/matan/.atom/packages/autocomplete-clang/lib/autocomplete-clang-view.coffee:80:8)
  at AutocompleteClangView.module.exports.AutocompleteClangView.handleChanged (/home/matan/.atom/packages/autocomplete-clang/lib/autocomplete-clang-view.coffee:69:12)
  at /home/matan/.atom/packages/autocomplete-clang/lib/autocomplete-clang-view.coffee:41:47
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at TextBuffer.module.exports.TextBuffer.applyPatch (/usr/share/atom/resources/app/node_modules/text-buffer/lib/text-buffer.js:590:20)
  at TextBuffer.module.exports.TextBuffer.setTextInRange (/usr/share/atom/resources/app/node_modules/text-buffer/lib/text-buffer.js:503:12)
  at Selection.module.exports.Selection.insertText (/usr/share/atom/resources/app/src/selection.js:446:43)
  at /usr/share/atom/resources/app/src/text-editor.js:738:31
  at /usr/share/atom/resources/app/src/text-editor.js:777:27
  at History.module.exports.History.transact (/usr/share/atom/resources/app/node_modules/text-buffer/lib/history.js:112:18)
  at TextBuffer.module.exports.TextBuffer.transact (/usr/share/atom/resources/app/node_modules/text-buffer/lib/text-buffer.js:683:27)
  at TextEditor.module.exports.TextEditor.transact (/usr/share/atom/resources/app/src/text-editor.js:1146:26)
  at TextEditor.module.exports.TextEditor.mutateSelectedText (/usr/share/atom/resources/app/src/text-editor.js:770:19)
  at TextEditor.module.exports.TextEditor.insertText (/usr/share/atom/resources/app/src/text-editor.js:735:21)
  at TextEditor.object.(anonymous function) [as insertText] (/usr/share/atom/resources/app/node_modules/underscore-plus/lib/underscore-plus.js:70:27)
  at /usr/share/atom/resources/app/src/text-editor-component.js:653:23
  at History.module.exports.History.transact (/usr/share/atom/resources/app/node_modules/text-buffer/lib/history.js:112:18)
  at TextBuffer.module.exports.TextBuffer.transact (/usr/share/atom/resources/app/node_modules/text-buffer/lib/text-buffer.js:683:27)
  at TextEditor.module.exports.TextEditor.transact (/usr/share/atom/resources/app/src/text-editor.js:1146:26)
  at [object Object].module.exports.React.createClass.onTextInput (/usr/share/atom/resources/app/src/text-editor-component.js:652:30)
  at HTMLDivElement.boundMethod (/usr/share/atom/resources/app/node_modules/react-atom-fork/lib/ReactCompositeComponent.js:1295:21)

```

_Copied from original issue: atom/atom#4500_

**Comment by codefingas** [comment]
What is happening is that you don't have an optionText  prop passed.
You can pass a function to the props like so:
<Autocomplete optionText={choice => `${choice.name || ''}`}/>
