### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by haular20** [yasuyuky/autocomplete-clang#32]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.175.0
**System**: linux 3.13.0-32-generic
**Thrown From**: [autocomplete-clang](https://github.com/yasuyuky/autocomplete-clang) package, v0.6.1

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /home/haular/.atom/packages/autocomplete-clang/lib/util.coffee:18

TypeError: undefined is not a function
  at Object.module.exports.getFirstCursorScopes (/home/haular/.atom/packages/autocomplete-clang/lib/util.coffee:18:34)
  at Object.module.exports.getFirstCursorSourceScopeLang (/home/haular/.atom/packages/autocomplete-clang/lib/util.coffee:14:15)
  at Object.module.exports.emitPch (/home/haular/.atom/packages/autocomplete-clang/lib/autocomplete-clang.coffee:142:17)
  at atom-text-editor.deactivationDisposables.add.atom.commands.add.autocomplete-clang:emit-pch (/home/haular/.atom/packages/autocomplete-clang/lib/autocomplete-clang.coffee:139:10)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/opt/atom/resources/app/src/command-registry.js:243:29)
  at CommandRegistry.handleCommandEvent (/opt/atom/resources/app/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/opt/atom/resources/app/src/command-registry.js:156:19)
  at Ipc.<anonymous> (/opt/atom/resources/app/src/window-event-handler.js:65:30)
  at Ipc.emit (events.js:107:17)
  at process.<anonymous> (/opt/atom/resources/atom/renderer/api/lib/ipc.js:22:29)
  at process.emit (events.js:110:17)

```

### Commands

```
     -30:20.7 application:open-file (atom-text-editor.editor)
     -30:05.8 core:backspace (atom-text-editor.editor.is-focused)
     -30:05.4 tree-view:toggle (atom-text-editor.editor.is-focused)
     -30:00.0 autocomplete-clang:emit-pch (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "metrics"
    ],
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ],
    "autoHideMenuBar": true
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-clang, v0.6.1
build, v0.23.3

# Dev
No dev packages
```

/cc @atom/core

**Comment by dschwen** [comment]
This is easy to reproduce:

1. File -> New File
2. Packages -> Autocomplete Clang -> Emit Precompiled Header

**Comment by dschwen** [comment]
Looks like in utils.coffee line 18

```
firstCursorPosition = editor.getCursors()[0].getBufferPosition()
```

```editor``` does not have the ```getCursors``` method :-/

**Comment by gnzlbg** [comment]
I get this error when trying to `autocomplete: next`:

```bash
/Users/gnzlbg/.atom/packages/autocomplete-clang/lib/autocomplete-clang.coffee:113
Hide Stack Trace
TypeError: undefined is not a function
  at /Users/gnzlbg/.atom/packages/autocomplete-clang/lib/autocomplete-clang.coffee:113:57
  at atom-text-editor.deactivationDisposables.add.atom.commands.add.autocomplete:next (/Users/gnzlbg/.atom/packages/autocomplete-clang/lib/autocomplete-clang.coffee:76:29)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/Applications/Atom.app/Contents/Resources/app/node_modules/command-palette/lib/command-palette-view.js:120:32)
  at CommandPaletteView.module.exports.SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app/node_modules/command-palette/node_modules/atom-space-pen-views/lib/select-list-view.js:335:21)
  at space-pen-div.atom.commands.add.core:confirm (/Applications/Atom.app/Contents/Resources/app/node_modules/command-palette/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:172:20)
```

**Comment by arayaq** [comment]
Enter steps to reproduce below:

1. Open project
2. Try to emit precompiled header

**Atom Version**: 0.186.0
**System**: linux 3.16.0-31-generic
**Thrown From**: [autocomplete-clang](https://github.com/yasuyuky/autocomplete-clang) package, v0.6.2

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /home/arayaq/.atom/packages/autocomplete-clang/lib/util.coffee:18

TypeError: undefined is not a function
    at Object.module.exports.getFirstCursorScopes (/home/arayaq/.atom/packages/autocomplete-clang/lib/util.coffee:24:36)
    at Object.module.exports.getFirstCursorSourceScopeLang (/home/arayaq/.atom/packages/autocomplete-clang/lib/util.coffee:19:21)
    at Object.module.exports.emitPch (/home/arayaq/.atom/packages/autocomplete-clang/lib/autocomplete-clang.coffee:94:19)
    at atom-text-editor.deactivationDisposables.add.atom.commands.add.autocomplete-clang:emit-pch (/home/arayaq/.atom/packages/autocomplete-clang/lib/autocomplete-clang.coffee:87:26)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/opt/atom/resources/app/src/command-registry.js:243:29)
    at /opt/atom/resources/app/src/command-registry.js:3:61
    at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/opt/atom/resources/app/node_modules/command-palette/lib/command-palette-view.js:120:32)
    at CommandPaletteView.module.exports.SelectListView.confirmSelection (/opt/atom/resources/app/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
    at space-pen-div.atom.commands.add.core:confirm (/opt/atom/resources/app/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/opt/atom/resources/app/src/command-registry.js:243:29)
```

### Commands

```
     -0:50.3 command-palette:toggle (atom-text-editor.editor.is-focused)
  6x -0:48.4 core:move-down (atom-text-editor.editor.mini)
     -0:42.3 editor:consolidate-selections (atom-text-editor.editor.mini)
     -0:42.3 core:cancel (atom-text-editor.editor.mini)
     -0:41.3 go-to-line:toggle (atom-text-editor.editor.is-focused)
     -0:41.1 fuzzy-finder:toggle-buffer-finder (atom-text-editor.editor.mini)
     -0:39.6 editor:consolidate-selections (atom-text-editor.editor.mini)
     -0:39.6 core:cancel (atom-text-editor.editor.mini)
  2x -0:38.8 go-to-line:toggle (atom-workspace.workspace.scrollbars-visible-always.theme-atom-light-syntax.theme-unity-ui)
     -0:27.6 open-on-github:blame (atom-workspace.workspace.scrollbars-visible-always.theme-atom-light-syntax.theme-unity-ui)
  2x -0:21.6 editor:move-to-beginning-of-word (atom-text-editor.editor.is-focused)
     -0:17.2 command-palette:toggle (atom-text-editor.editor.is-focused)
 13x -0:15.1 core:move-down (atom-text-editor.editor.mini)
     -0:01.5 core:move-up (atom-text-editor.editor.mini)
     -0:00.8 core:confirm (atom-text-editor.editor.mini)
     -0:00.8 autocomplete-clang:emit-pch (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "unity-ui",
      "atom-light-syntax"
    ],
    "disabledPackages": [
      "metrics"
    ]
  },
  "autocomplete-clang": {
    "preCompiledHeaders": {},
    "std": {}
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-clang, v0.6.2
autocomplete-plus, v2.4.1
git-log, v0.3.0
git-projects, v1.8.1
go-format, v1.0.7
go-plus, v3.2.3
unity-ui, v2.0.5

# Dev
No dev packages
```
