### ISSUE TITLE
Error with autocomplete:next

### ISSUE THREAD

**Issue by gnzlbg** [yasuyuky/autocomplete-clang#38]
Somehow when I hit `ctrl + alt + /` under mac nothing happens. 
I also have auto toggle enabled but nothing happens either when I hit any of the default auto toggle keys.

I tried using `cmd + shift + p -> autocomplete-clang:toggle`  but nothing happens either.

The test program I'm using is:

``` c++
struct A { int member; };
int main() {
  A a;
  a. /* hit autocomplete-clang:toggle here, expect member */;
  return 0;
}
```

I tried using `cmd + shift + p -> autocomplete:next` but then I get the following error:

``` bash
/Users/gnzlbg/.atom/packages/autocomplete-clang/lib/autocomplete-clang.coffee:113
Hide Stack Trace
TypeError: undefined is not a function
  at /Users/gnzlbg/.atom/packages/autocomplete-clang/lib/autocomplete-clang.coffee:113:57
  at atom-text-editor.deactivationDisposables.add.atom.commands.add.autocomplete:next (/Users/gnzlbg/.atom/packages/autocomplete-clang/lib/autocomplete-clang.coffee:76:29)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/Applications/Atom.app/Contents/Resources/app/node_modules/command-palette/lib/command-palette-view.js:120:32)
  at CommandPaletteView.module.exports.SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
  at space-pen-div.atom.commands.add.core:confirm (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:558:16)
```

**Comment by yasuyuky** [comment]
Thanks for the feedback.
Curiously, the completion works on the same code in my environment.

![autocomplete-clang - atom 2015-03-18 01-19-58](https://cloud.githubusercontent.com/assets/5463365/6692010/6b78605a-cd0d-11e4-94df-7213e08e0f1b.png)

To clarify the problem, could you tell me the result of Key Binding Resolver (`cmd-.`) when `ctrl+alt+/` is hit.

**Comment by gnzlbg** [comment]
autocomplete-clang:toggle   atom-workspace
/.../.atom/packages/autocomplete-clang/keymaps/autocomplete-clang.cson

What is your evinronment?

**Comment by gnzlbg** [comment]
Since nothing happens when i hit `ctrl+alt+/` but it seems that the right command is found, is there a way to debug what the command is doing?

**Comment by gnzlbg** [comment]
I got it to work as expected by using as my clang command just `clang++`.

Before I had `/usr/local/clang++ -std=c++1y -Wall -Werror -nostdinc++ -stdlib=libc++` and In the include sections I had `path_to_libcxx_include, path_to_eigen3_include, ...`. I'm trying to find out why that does not work. It seems like `clang++ -std=c++1y` and `clang++ -std=c++11` already fail, but `/usr/local/bin/clang++` works.

**Comment by gnzlbg** [comment]
This is my new minimal test case that still doesn't work:

```c++
struct A { 
  int member; 
  double foo(int a, double d) { return a + d; }
};
int main() {
  A a;
  a.member = 3;
  auto v = [&](){ return a. /* hit ctr-alt-/ here doesn't work */ }();
  return 0;
}
```

I've tried moving the flags to a `.clang_complete` file without luck. This is the contents of that file

```bash
-Wall -Werror -std=c++1y -nostdinc++ -stdlib=libc++ -I/Users/gnzlbg/src/env/include/libcxx -I/Users/gnzlbg/src/env/include
```

**Comment by gnzlbg** [comment]
I partially fixed this by adding to `config.cson` under `.atom`:

```cson
  "autocomplete-clang":
    preCompiledHeaders: {}
    std: "c++" : "c++1y"
    clangCommand: "/usr/local/bin/clang++"
```

It would be nice if there was a way to just pass the standard to use via a command line option.

**Comment by yasuyuky** [comment]
Thanks for your detailed feedbacks and good suggestions.
I'll consider about them.

**Comment by gnzlbg** [comment]
If you have any ideas about how to get started with any of them, I might
give it a try :)
