### ISSUE TITLE
Uncaught Error: No transaction is open

### ISSUE THREAD

**Issue by TheLumaio** [yasuyuky/autocomplete-clang#39]
[Enter steps to reproduce below:]

1. Entered "#include "
2. Hit tab

**Atom Version**: 0.183.0
**System**: Microsoft Windows 8.1 Pro
**Thrown From**: [autocomplete-clang](https://github.com/yasuyuky/autocomplete-clang) package, v0.6.2

### Stack Trace

Uncaught Error: No transaction is open

```
At C:\Users\lumaio\AppData\Local\atom\app-0.183.0\resources\app\node_modules\text-buffer\lib\history.js:159

Error: No transaction is open
  at History.module.exports.History.abortTransaction (C:\Users\lumaio\AppData\Local\atom\app-0.183.0\resources\app\node_modules\text-buffer\lib\history.js:159:15)
  at TextBuffer.module.exports.TextBuffer.abortTransaction (C:\Users\lumaio\AppData\Local\atom\app-0.183.0\resources\app\node_modules\text-buffer\lib\text-buffer.js:702:27)
  at TextEditor.module.exports.TextEditor.abortTransaction (C:\Users\lumaio\AppData\Local\atom\app-0.183.0\resources\app\src\text-editor.js:1221:26)
  at AutocompleteClangView.module.exports.AutocompleteClangView.cancelled (C:\Users\lumaio\.atom\packages\autocomplete-clang\lib\autocomplete-clang-view.coffee:148:15)
  at AutocompleteClangView.module.exports.SelectListView.cancel (C:\Users\lumaio\.atom\packages\autocomplete-clang\node_modules\atom-space-pen-views\lib\select-list-view.coffee:232:6)
  at atom-text-editor.<anonymous> (C:\Users\lumaio\.atom\packages\autocomplete-clang\node_modules\atom-space-pen-views\lib\select-list-view.coffee:36:8)
  at atom-text-editor.jQuery.event.dispatch (C:\Users\lumaio\.atom\packages\autocomplete-clang\node_modules\atom-space-pen-views\node_modules\space-pen\vendor\jquery.js:4676:9)
  at atom-text-editor.elemData.handle (C:\Users\lumaio\.atom\packages\autocomplete-clang\node_modules\atom-space-pen-views\node_modules\space-pen\vendor\jquery.js:4360:46)

```

### Commands

```
     -3:11.6 settings-view:open (atom-text-editor.editor.is-focused)
     -0:50.9 core:confirm (atom-text-editor#autocomplete-clang.clangCommand.editor.mini)
     -0:26.6 core:select-all (atom-text-editor#autocomplete-clang.includePaths.editor.mini)
     -0:26.4 core:paste (atom-text-editor#autocomplete-clang.includePaths.editor.mini)
     -0:24.4 core:save (atom-text-editor#autocomplete-clang.includePaths.editor.mini)
     -0:23.6 core:close (atom-text-editor#autocomplete-clang.includePaths.editor.mini)
     -0:21.4 core:save (atom-text-editor.editor.is-focused)
  3x -0:04.0 core:backspace (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "deep-syntax"
    ]
  },
  "autocomplete-clang": {
    "preCompiledHeaders": {},
    "std": {},
    "clangCommand": "clang  ",
    "includePaths": [
      "C:\\MinGW\\x86_64-w64-mingw32\\include"
    ]
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-clang, v0.6.2
deep-syntax, v0.1.0
language-glsl, v1.0.1
language-lua, v0.9.0
linter, v0.11.1
linter-lua, v0.1.3
script, v2.16.0

# Dev
No dev packages
```

**Comment by lolzballs** [comment]
I also had this happen when trying to access the members of the glm::vec3 type.

**Comment by kolis** [comment]
I get the same error when pressing space when the autocomplete list appears
eg: 
* type "foo->"
* autocomplete list pops up
* press space

**Comment by fulldecent** [comment]
Confirmed Mac 0.192.0

**Comment by shahril96** [comment]
Confirmed Ubuntu 14.04

**Comment by yasuyuky** [comment]
solved
