### ISSUE TITLE
Uncaught Error: write EPIPE

### ISSUE THREAD

**Issue by Smouking** [yasuyuky/autocomplete-clang#62]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 0.204.0
**System**: Unknown Windows Version
**Thrown From**: [autocomplete-clang](https://github.com/yasuyuky/autocomplete-clang) package, v0.7.0
### Stack Trace

Uncaught Error: write EPIPE

```
At events.js:141

Error: write EPIPE
  at exports._errnoException (util.js:734:11)
  at Socket._writeGeneric (net.js:668:26)
  at Socket._write (net.js:687:8)
  at doWrite (_stream_writable.js:295:12)
  at writeOrBuffer (_stream_writable.js:282:5)
  at Socket.Writable.write (_stream_writable.js:210:11)
  at Socket.write (net.js:612:40)
  at Object.module.exports.emitPch (C:\Users\dima5_000\.atom\packages\autocomplete-clang\lib\autocomplete-clang.coffee:187:24)
  at atom-text-editor.deactivationDisposables.add.atom.commands.add.autocomplete-clang:emit-pch (C:\Users\dima5_000\.atom\packages\autocomplete-clang\lib\autocomplete-clang.coffee:172:10)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\dima5_000\AppData\Local\atom\app-0.204.0\resources\app.asar\src\command-registry.js:238:29)
  at CommandRegistry.handleCommandEvent (C:\Users\dima5_000\AppData\Local\atom\app-0.204.0\resources\app.asar\src\command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (C:\Users\dima5_000\AppData\Local\atom\app-0.204.0\resources\app.asar\src\command-registry.js:153:19)
  at EventEmitter.<anonymous> (C:\Users\dima5_000\AppData\Local\atom\app-0.204.0\resources\app.asar\src\window-event-handler.js:71:30)
  at emitOne (events.js:77:13)
  at EventEmitter.emit (events.js:166:7)

```
### Commands

```
     -3:29.6.0 core:save (atom-text-editor.editor.is-focused)
  2x -3:18.5.0 window:toggle-full-screen (atom-text-editor.editor.is-focused)
     -2:59.4.0 bracket-matcher:go-to-matching-bracket (atom-text-editor.editor.is-focused)
  2x -2:56.4.0 bracket-matcher:select-inside-brackets (atom-text-editor.editor.is-focused)
     -2:50.4.0 bracket-matcher:go-to-matching-bracket (atom-text-editor.editor.is-focused)
     -2:45 open-on-github:blame (atom-text-editor.editor.is-focused)
     -2:39.9.0 tree-view:toggle-focus (atom-text-editor.editor.is-focused)
     -1:05.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  7x -0:57.5.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:53.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  2x -0:28.1.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:26.1.0 autocomplete-plus:activate (atom-text-editor.editor.is-focused)
  2x -0:24.7.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:24.2.0 core:save (atom-text-editor.editor.is-focused)
     -0:17.7.0 autocomplete-clang:toggle (atom-text-editor.editor.is-focused)
     -0:14.4.0 autocomplete-clang:emit-pch (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-light-ui",
      "one-dark-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
autocomplete-clang, v0.7.0
language-cmake, v0.1.3
racer, v0.11.0

# Dev
No dev packages
```

**Comment by yasuyuky** [comment]
Thanks for your feedback.

Is there `clang` command in your `$PATH`?

**Comment by Smouking** [comment]
> Is there clang command in your $PATH?

yes

**Comment by BrianSidebotham** [comment]
This is triggered by attempting to put in custom commands arguments in the Clang Command setting. I was looking to add `-pthread` for generating pch for example and so ended up putting `clang -pthread` in the Clang command setting
