### ISSUE TITLE
Failed to activate the autocomplete-clang package

### ISSUE THREAD

**Issue by bazhenovc** [yasuyuky/autocomplete-clang#78]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.18
**System**: Unknown Windows Version
**Thrown From**: [autocomplete-clang](https://github.com/yasuyuky/autocomplete-clang) package, v0.8.7

### Stack Trace

Failed to activate the autocomplete-clang package

```
At Cannot find module 'clang-flags'

Error: Cannot find module 'clang-flags'
  at Module._resolveFilename (module.js:334:15)
  at Function.Module._resolveFilename (C:\Users\Кирилл\AppData\Local\atom\app-1.0.18\resources\app.asar\src\module-cache.js:383:52)
  at Function.Module._load (module.js:284:25)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Object.<anonymous> (C:\Users\Кирилл\.atom\packages\autocomplete-clang\lib\clang-provider.coffee:8:14)
  at Object.<anonymous> (C:\Users\Кирилл\.atom\packages\autocomplete-clang\lib\clang-provider.coffee:5:1)
  at Module._compile (module.js:428:26)
  at Object.defineProperty.value [as .coffee] (C:\Users\Кирилл\AppData\Local\atom\app-1.0.18\resources\app.asar\src\compile-cache.js:169:21)
  at Module.load (module.js:353:32)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Object.module.exports.provide (C:\Users\Кирилл\.atom\packages\autocomplete-clang\lib\autocomplete-clang.coffee:100:22)
  at Package.module.exports.Package.activateServices (C:\Users\Кирилл\AppData\Local\atom\app-1.0.18\resources\app.asar\src\package.js:416:69)
  at Package.module.exports.Package.activateNow (C:\Users\Кирилл\AppData\Local\atom\app-1.0.18\resources\app.asar\src\package.js:248:16)
  at C:\Users\Кирилл\AppData\Local\atom\app-1.0.18\resources\app.asar\src\package.js:226:30
  at Package.module.exports.Package.measure (C:\Users\Кирилл\AppData\Local\atom\app-1.0.18\resources\app.asar\src\package.js:169:15)
  at Package.module.exports.Package.activate (C:\Users\Кирилл\AppData\Local\atom\app-1.0.18\resources\app.asar\src\package.js:218:14)
  at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\Кирилл\AppData\Local\atom\app-1.0.18\resources\app.asar\src\package-manager.js:486:21)
  at C:\Users\Кирилл\AppData\Local\atom\app-1.0.18\resources\app.asar\node_modules\settings-view\lib\package-manager.js:371:29
  at exit (C:\Users\Кирилл\AppData\Local\atom\app-1.0.18\resources\app.asar\node_modules\settings-view\lib\package-manager.js:60:16)
  at triggerExitCallback (C:\Users\Кирилл\AppData\Local\atom\app-1.0.18\resources\app.asar\src\buffered-process.js:213:47)
  at ChildProcess.<anonymous> (C:\Users\Кирилл\AppData\Local\atom\app-1.0.18\resources\app.asar\src\buffered-process.js:235:18)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:172:7)
  at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)

```

### Commands

```
     -3:15 core:cancel (atom-text-editor.editor.is-focused)
     -3:14.7.0 core:move-down (atom-text-editor.editor.is-focused)
  3x -3:14.4.0 core:page-down (atom-text-editor.editor.is-focused)
  2x -3:13.5.0 core:page-up (atom-text-editor.editor.is-focused)
     -2:59.9.0 autocomplete-plus:activate (atom-text-editor#editor.fontFamily.editor.mini.is-focused)
     -2:54.2.0 editor:select-to-first-character-of-line (atom-text-editor#editor.fontFamily.editor.mini.is-focused)
 15x -2:50.7.0 core:backspace (atom-text-editor#editor.fontFamily.editor.mini.is-focused)
     -2:10.1.0 core:select-all (atom-text-editor#editor.fontFamily.editor.mini.is-focused)
  2x -2:09.6.0 core:backspace (atom-text-editor#editor.fontFamily.editor.mini.is-focused)
     -2:04.1.0 core:select-all (atom-text-editor#editor.fontFamily.editor.mini.is-focused)
  4x -1:46.6.0 core:backspace (atom-text-editor#editor.fontSize.editor.mini.is-focused)
     -1:31.7.0 core:select-all (atom-text-editor#editor.fontFamily.editor.mini.is-focused)
  6x -1:31.5.0 core:backspace (atom-text-editor#editor.fontFamily.editor.mini.is-focused)
     -0:46.2.0 core:select-all (atom-text-editor#editor.fontFamily.editor.mini.is-focused)
  5x -0:44.5.0 core:backspace (atom-text-editor#editor.fontFamily.editor.mini.is-focused)
     -0:22.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ],
    "autoHideMenuBar": true
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-clang, v0.8.7

# Dev
No dev packages
```

**Comment by Zhomart** [comment]
Go to `autocomplete-clang` directory and run `$ apm install`. It installs `clang-flags`.
I've got same error when I linked. I've cloned this repo and did `$ apm link`. Then I run `$ apm install` and now it works.

**Comment by bazhenovc** [comment]
apm install did the trick, thanks a lot!
